CREATE TABLE IF NOT EXISTS esi_cache (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  scope_key VARCHAR(128) NOT NULL,
  cache_key CHAR(64) NOT NULL,
  url TEXT NOT NULL,
  payload_json MEDIUMTEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ttl_seconds INT NOT NULL DEFAULT 3600,
  status_code INT NOT NULL DEFAULT 200,
  etag VARCHAR(128) NULL,
  UNIQUE KEY uniq_scope_cache (scope_key, cache_key),
  KEY idx_scope (scope_key),
  KEY idx_fetched (fetched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE esi_cache ADD COLUMN IF NOT EXISTS url TEXT NOT NULL;
ALTER TABLE esi_cache ADD COLUMN IF NOT EXISTS status_code INT NOT NULL DEFAULT 200;
ALTER TABLE esi_cache ADD COLUMN IF NOT EXISTS etag VARCHAR(128) NULL;
ALTER TABLE esi_cache ADD COLUMN IF NOT EXISTS ttl_seconds INT NOT NULL DEFAULT 3600;
ALTER TABLE esi_cache ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

