ALTER TABLE eve_tokens
  MODIFY expires_at DATETIME NULL,
  ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN last_refresh_at DATETIME NULL,
  ADD COLUMN error_last TEXT NULL;

ALTER TABLE eve_token_buckets
  ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN last_refresh_at DATETIME NULL,
  ADD COLUMN error_last TEXT NULL;
