ALTER TABLE eve_tokens
  MODIFY expires_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS last_refresh_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS error_last TEXT NULL;

ALTER TABLE eve_token_buckets
  ADD COLUMN IF NOT EXISTS status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS last_refresh_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS error_last TEXT NULL;
