-- Preferred fix: ensure schema matches code that writes created_at/updated_at.
ALTER TABLE module_secgroups_groups
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE module_secgroups_group_filters
  ADD COLUMN IF NOT EXISTS enabled TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS last_evaluated_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS last_pass TINYINT(1) NULL,
  ADD COLUMN IF NOT EXISTS last_message VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS last_user_id BIGINT UNSIGNED NULL;
